exports.URL = {
    HOME: "/",
    LOGIN: "/login",
    DASHBOARDUSER: "/dashboard",
    REGISTER: "/register",
    DETAIL: "/detail/:id",
    BOOKING: "/detail/booking/:id",
    RESETPASSWORD: "/reset-password",
    ABOUT: "/aboutUs",
    PROFILE: "/profile/:id",
    SEARCH: "/search",
    ADMIN: "/admin",
    CHECKOUT:"/detail/booking/checkout",
    CINEPLEX:"/cineplex",
    HISTORY:"/history",
    VERIFY:"/verify",
  };